# NeoForge mods.toml file for Eldritch Core
# Documentation: https://neoforged.net/docs/configuration/mods.toml/

modLoader="javafml"
loaderVersion="[7,)"
license="MIT"
issueTrackerURL="https://github.com/yourusername/eldritchvoid/issues"

[[mods]]
modId="eldritchvoid"
version="${file.jarVersion}"
displayName="Eldritch Core"
updateJSONURL="https://example.com/updates.json"
displayURL="https://example.com/eldritchvoid"
logoFile="logo.png"
credits="Thanks to all contributors and the NeoForge team"
authors="Your Name"
description='''
The core module for Eldritch Void, providing common APIs and utilities for all other modules.

This module is required by all other Eldritch Void modules.
'''

[[dependencies.eldritchvoid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.5,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.eldritchvoid]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.5.0,22.0.0)"
    ordering="NONE"
    side="BOTH"