# NeoForge mods.toml file for Void Corruption module
# Documentation: https://neoforged.net/docs/configuration/mods.toml/

modLoader="javafml"
loaderVersion="[7,)"
license="MIT"
issueTrackerURL="https://github.com/yourusername/eldritchvoid/issues"

[[mods]]
modId="eldritchvoid_voidcorruption"
version="${file.jarVersion}"
displayName="Eldritch Void - Void Corruption"
updateJSONURL="https://example.com/updates.json"
displayURL="https://example.com/eldritchvoid"
logoFile="logo.png"
credits="Thanks to all contributors and the NeoForge team"
authors="Your Name"
description='''
The Void Corruption module for Eldritch Void.

Features corrupted landscapes, entities, and status effects related to void energy exposure.
'''

[[dependencies.eldritchvoid_voidcorruption]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.5,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.eldritchvoid_voidcorruption]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.5.0,22.0.0)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.eldritchvoid_voidcorruption]]
    modId="eldritchvoid"
    mandatory=true
    versionRange="[0.1.0,)"
    ordering="AFTER"
    side="BOTH"