modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/yourusername/eldritchvoid/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://github.com/yourusername/eldritchvoid/raw/main/update.json"
displayURL="https://github.com/yourusername/eldritchvoid"
logoFile="eldritchvoid_logo.png"
credits="Thanks to Azanor for the original Thaumcraft mod that inspired this project"
authors="${mod_authors}"
description='''
A comprehensive modular Minecraft mod featuring Eldritch, Void, and Obsidian themes inspired by Thaumcraft.

Features:
- Modular architecture with 10 integrated modules
- Void Alchemy with fluid systems
- Obsidian Forgemaster with custom crafting
- Eldritch Artifacts with procedural shrines
- And much more!
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"